#!/usr/bin/env python3
# MACDART port of runtime/tools/create_resources.py (originally Python 2).
#
# Bundles resource files (the vmservice Dart sources) into a C++ source file as
# byte-array string literals plus a `ResourcesEntry __<table>_resources_[]`
# table, consumed by bin/vmservice_impl.cc. Only the service isolate uses this;
# a plain `dart script.dart` never reads it, but the symbols must link.
#
# Py3 fixes: bytes iteration (no ord()), `except E as e`, deterministic header.
from __future__ import annotations

import argparse
import os
import re
import sys
import zlib


def _norm(p: str) -> str:
    """Canonicalize a path to forward slashes (Windows paths arrive with
    backslashes from gen_sources, but CMake passes root_prefix forward-sliced)."""
    return os.path.normpath(p).replace("\\", "/")


def make_resources(root_dir, input_files, table_name, compress, no_compress_exts):
    result = ""
    resources = []
    # Normalize the root prefix and re-add the trailing slash normpath drops, so
    # the prefix strip is separator- and (on Windows) drive-case-insensitive.
    root_norm = _norm(root_dir) if root_dir else ""
    if root_norm and not root_norm.endswith("/"):
        root_norm += "/"
    for resource_file in input_files:
        rf_norm = _norm(resource_file)
        if root_norm and rf_norm.lower().startswith(root_norm.lower()):
            name = rf_norm[len(root_norm):]     # e.g. "vmservice/loader.dart"
        else:
            name = rf_norm
        _, ext = os.path.splitext(resource_file)
        do_compress = compress and ext not in no_compress_exts
        with open(resource_file, "rb") as fh:
            data = fh.read()
        if do_compress:
            data = zlib.compress(data)
        # Emit a VALID C identifier: every char outside [A-Za-z0-9_] -> '_'
        # (the original regex missed ':' from a Windows drive letter, and only
        # fired at all when the prefix strip failed to remove the drive path).
        sym = re.sub(r"[^0-9A-Za-z_]", "_", name) + "_"
        result += "// %s\n" % name
        result += "const char " + sym + "[] = {\n   "
        counter = 0
        for byte in data:  # Py3: ints
            result += r" '\x%02x'," % byte
            counter += 1
            if counter == 10:
                result += "\n   "
                counter = 0
        if counter != 0:
            result += "\n   "
        result += " 0\n};\n\n"
        resources.append(("/" + name, sym, len(data)))

    result += "ResourcesEntry __%s_resources_[] = {\n" % table_name
    for url, sym, length in resources:
        result += '   { "%s", %s, %d },\n' % (url, sym, length)
    result += "   { 0, 0, 0 },\n};\n\n"
    return result


def main(argv) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--output", required=True)
    p.add_argument("--root_prefix", default="")
    p.add_argument("--outer_namespace", default="dart")
    p.add_argument("--inner_namespace", default=None)
    p.add_argument("--table_name", required=True)
    p.add_argument("--compress", action="store_true")
    p.add_argument("--no_compress_extensions", action="append", default=[".dart"])
    p.add_argument("inputs", nargs="+")
    args = p.parse_args(argv[1:])
    try:
        text = (
            "// Generated by MACDART create_resources.py. Do not edit.\n\n"
            "namespace %s {\n" % args.outer_namespace
        )
        if args.inner_namespace is not None:
            text += "namespace %s {\n" % args.inner_namespace
        text += (
            "\nstruct ResourcesEntry {\n"
            "  const char* path_;\n"
            "  const char* resource_;\n"
            "  int length_;\n"
            "};\n\n"
        )
        text += make_resources(args.root_prefix, args.inputs, args.table_name,
                               args.compress, args.no_compress_extensions)
        if args.inner_namespace is not None:
            text += "}  // namespace %s\n" % args.inner_namespace
        text += "}  // namespace %s\n" % args.outer_namespace
        with open(args.output, "w") as out:
            out.write(text)
        return 0
    except Exception as e:  # noqa: BLE001
        sys.stderr.write("create_resources.py exception\n")
        sys.stderr.write(str(e) + "\n")
        return -1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
